services:
  bot:
    container_name: royalrumblediscordbot-bot
    image: morenicano/royalrumbledrawingdiscordbot
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    networks:
      - default
    depends_on:
      - db
  web:
    container_name: royalrumblediscordbot-web
    image: morenicano/royalrumbledrawingdiscordbot
    ports:
      - 32797:8000/tcp
    networks:
      - default
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
  db:
    container_name: royalrumblediscordbot-db
    image: postgres  # Use PostgreSQL image
    networks:
      - default
    ports:
      - 32796:5432/tcp
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:

networks:
  default:
    name: rrddb
    external: false